<a href="https://colab.research.google.com/github/SanketDevmunde/NLP_ASSIGNMENT/blob/main/NLP_Assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Install necessary libraries
!pip install -U nltk gensim scikit-learn

# Import required libraries
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer
from gensim.models import Word2Vec
import nltk
import numpy as np
nltk.download('punkt_tab')


# Sample documents
documents = [
    "This is the first document.",
    "This document is the second document.",
    "And this is the third one."
]

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


In [ ]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(documents)
count_matrix = X.toarray()  # Convert sparse matrix to NumPy array

print("Count Occurrence Matrix:\n", count_matrix)

Count Occurrence Matrix:
 [[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]]


In [ ]:
tf_normalized = count_matrix / count_matrix.sum(axis=1, keepdims=True)
print("\nNormalized Count Occurrence (TF):\n", np.round(tf_normalized, 3))



Normalized Count Occurrence (TF):
 [[0.    0.2   0.2   0.2   0.    0.    0.2   0.    0.2  ]
 [0.    0.333 0.    0.167 0.    0.167 0.167 0.    0.167]
 [0.167 0.    0.    0.167 0.167 0.    0.167 0.167 0.167]]


In [ ]:
tfidf_transformer = TfidfTransformer()
tfidf_matrix = tfidf_transformer.fit_transform(count_matrix).toarray()

print("\nTF-IDF Matrix:\n", np.round(tfidf_matrix, 3))


TF-IDF Matrix:
 [[0.    0.469 0.617 0.365 0.    0.    0.365 0.    0.365]
 [0.    0.728 0.    0.283 0.    0.479 0.283 0.    0.283]
 [0.497 0.    0.    0.294 0.497 0.    0.294 0.497 0.294]]


In [ ]:
# Function to tokenize text
def tokenize_text(text):
    return nltk.word_tokenize(text.lower())

# Tokenizing the documents
tokenized_documents = [tokenize_text(doc) for doc in documents]

# Train Word2Vec model
word2vec_model = Word2Vec(sentences=tokenized_documents, vector_size=100, window=5, min_count=1, workers=4)

# Example: Get word embedding for "document"
word_embedding = word2vec_model.wv['document']
print("\nEmbedding for 'document':\n", word_embedding)


Embedding for 'document':
 [-8.6204959e-03  3.6656798e-03  5.1890435e-03  5.7413341e-03
  7.4667106e-03 -6.1669527e-03  1.1071442e-03  6.0478016e-03
 -2.8417453e-03 -6.1734831e-03 -4.1064565e-04 -8.3685964e-03
 -5.6015723e-03  7.1051149e-03  3.3512993e-03  7.2244625e-03
  6.8005081e-03  7.5318469e-03 -3.7887152e-03 -5.6384038e-04
  2.3478975e-03 -4.5202258e-03  8.3918469e-03 -9.8565696e-03
  6.7639211e-03  2.9146592e-03 -4.9328543e-03  4.3973904e-03
 -1.7405687e-03  6.7118029e-03  9.9671669e-03 -4.3619340e-03
 -5.9958611e-04 -5.6970902e-03  3.8511248e-03  2.7869588e-03
  6.8903468e-03  6.1010849e-03  9.5382044e-03  9.2721898e-03
  7.9001701e-03 -6.9917394e-03 -9.1567943e-03 -3.5570699e-04
 -3.0986702e-03  7.8943772e-03  5.9379833e-03 -1.5462040e-03
  1.5110098e-03  1.7886526e-03  7.8182593e-03 -9.5115863e-03
 -2.0458201e-04  3.4695806e-03 -9.4097451e-04  8.3801365e-03
  9.0101836e-03  6.5338048e-03 -7.1310432e-04  7.7079539e-03
 -8.5331853e-03  3.2056449e-03 -4.6360181e-03 -5.0893556e